### ISSUE TITLE
Incompatible with Velocity

### ISSUE THREAD

**Issue by gam3rboy7** [DrexHD/VanillaPermissions#20]
Does not work on 1.21.1 when servers is behind velocity proxy.

`com.velocitypowered.proxy.util.except.QuietRuntimeException: A packet did not decode successfully (invalid data). For more information, launch Velocity with -Dvelocity.packet-decode-logging=true to see more.`

`at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity.jar:version]

[ERROR]: [server connection] player -> server: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@hashcode

io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket Direction CLIENTBOUND Protocol version State PLAY ID 11

	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:130) ~[velocity.jar:version]

	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:60) ~[velocity.jar:version]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[velocity.jar:version]

	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[velocity.jar:version]

	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity.jar:version]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[velocity.jar:version]

	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:85) ~[velocity.jar:version]

	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity.jar:version]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[velocity.jar:version]

	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[velocity.jar:version]

	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[velocity.jar:version]

	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[velocity.jar:version]

	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity.jar:version]

	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[velocity.jar:version]

	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[velocity.jar:version]

	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[velocity.jar:version]

	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity.jar:version]

	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[velocity.jar:version]

	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity.jar:version]

	at java.base/java.lang.Thread.run(Thread.java:1583) [?:version]

Caused by: java.lang.IllegalArgumentException: Unknown node type 3

	at com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket.deserializeNode(AvailableCommandsPacket.java:219) ~[velocity.jar:version]

	at com.velocitypowered.proxy.protocol.packet.AvailableCommandsPacket.decode(AvailableCommandsPacket.java:88) ~[velocity.jar:version]

	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity.jar:version]

	... 32 more

[INFO]: [server connection] player -> server has disconnected

[INFO]: [server connection] player -> lobby has connected

[INFO]: [server connection] player -> lobby has disconnected

[INFO]: [server connection] player -> server has connected

[INFO]: [server connection] player -> lobby has connected

[INFO]: [connected player] player (/local-ip:port) has connected
`

**Comment by DrexHD** [comment]
That's weird, please launch velocity with the mentioned `-Dvelocity.packet-decode-logging=true` flag to get some more information on the proplem.

**Comment by gam3rboy7** [comment]
Yes that is what the second part of the report shows

**Comment by DrexHD** [comment]
I am unable to reproduce this with just vanilla-permissions and velocity on default configs.

**Comment by gam3rboy7** [comment]
Ill do further testing, thanks.

**Comment by gam3rboy7** [comment]
It happens when using this plugin on velocity. This is a problem because my network is a hybrid of forge and fabric servers.

https://github.com/adde0109/Ambassador

**Comment by DrexHD** [comment]
I don't think I will provide support for this unless you could replicate it on just velocity, because this sounds like it might be a problem with the plugin then. Support from me for hybrids is also very limited.
