### ISSUE TITLE
Broken on 1.20

### ISSUE THREAD

**Issue by Binero** [DrexHD/VanillaPermissions#7]
vanilla-permissions-0.2.0+1.20.jar

```
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[17:21:15] [main/INFO]: Loading Minecraft 1.20 with Fabric Loader 0.14.21
[17:21:15] [ForkJoinPool-1-worker-2/WARN]: Mod plan uses the version 5.5 build 2397 which isn't compatible with Loader's extended semantic version format (Could not parse version number component '5 build 2397'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[17:21:15] [main/INFO]: Loading 68 mods:
        - com_github_llamalad7_mixinextras 0.2.0-beta.8
        - fabric-api 0.83.0+1.20
           |-- fabric-api-base 0.4.29+b04edc7a27
           |-- fabric-api-lookup-api-v1 1.6.34+4d8536c927
           |-- fabric-biome-api-v1 13.0.10+b3afc78b27
           |-- fabric-block-api-v1 1.0.9+e022e5d127
           |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b27
           |-- fabric-client-tags-api-v1 1.0.20+b3afc78b27
           |-- fabric-command-api-v1 1.2.32+f71b366f27
           |-- fabric-command-api-v2 2.2.11+b3afc78b27
           |-- fabric-commands-v0 0.2.49+df3654b327
           |-- fabric-containers-v0 0.1.61+df3654b327
           |-- fabric-content-registries-v0 4.0.7+b3afc78b27
           |-- fabric-convention-tags-v1 1.5.3+b3afc78b27
           |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe27
           |-- fabric-data-generation-api-v1 12.1.10+b3afc78b27
           |-- fabric-dimensions-v1 2.1.51+b3afc78b27
           |-- fabric-entity-events-v1 1.5.21+b3afc78b27
           |-- fabric-events-interaction-v0 0.6.0+b3afc78b27
           |-- fabric-events-lifecycle-v0 0.2.61+df3654b327
           |-- fabric-game-rule-api-v1 1.0.38+b04edc7a27
           |-- fabric-item-api-v1 2.1.26+b3afc78b27
           |-- fabric-item-group-api-v1 4.0.7+b3afc78b27
           |-- fabric-key-binding-api-v1 1.0.36+fb8d95da27
           |-- fabric-keybindings-v0 0.2.34+df3654b327
           |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b27
           |-- fabric-loot-api-v2 1.1.37+b3afc78b27
           |-- fabric-loot-tables-v1 1.1.41+9e7660c627
           |-- fabric-message-api-v1 5.1.6+b3afc78b27
           |-- fabric-mining-level-api-v1 2.1.47+b3afc78b27
           |-- fabric-models-v0 0.3.35+b3afc78b27
           |-- fabric-networking-api-v1 1.3.8+b3afc78b27
           |-- fabric-networking-v0 0.3.48+df3654b327
           |-- fabric-object-builder-api-v1 11.0.6+b3afc78b27
           |-- fabric-particles-v1 1.0.28+b3afc78b27
           |-- fabric-recipe-api-v1 1.0.18+b3afc78b27
           |-- fabric-registry-sync-v0 2.2.6+b3afc78b27
           |-- fabric-renderer-api-v1 3.0.1+b3afc78b27
           |-- fabric-renderer-indigo 1.3.1+b3afc78b27
           |-- fabric-renderer-registries-v1 3.2.44+df3654b327
           |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b27
           |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b27
           |-- fabric-rendering-v0 1.1.47+df3654b327
           |-- fabric-rendering-v1 3.0.6+b3afc78b27
           |-- fabric-resource-conditions-api-v1 2.3.4+b3afc78b27
           |-- fabric-resource-loader-v0 0.11.7+f7923f6d27
           |-- fabric-screen-api-v1 2.0.6+b3afc78b27
           |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b27
           |-- fabric-sound-api-v1 1.0.12+b3afc78b27
           |-- fabric-transfer-api-v1 3.2.2+b3afc78b27
           \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b27
        - fabric-language-kotlin 1.9.4+kotlin.1.8.21
           |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
           |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
           |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
           |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
           |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
           |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
           \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
        - fabricloader 0.14.21
        - java 17
        - luckperms 5.4.80
           \-- fabric-permissions-api-v0 0.2-SNAPSHOT
        - minecraft 1.20
        - vanilla-permissions 0.2.0+1.20
           |-- fabric-command-api-v2 2.2.11+b3afc78b27
           \-- fabric-permissions-api-v0 0.2-SNAPSHOT
[17:21:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[17:21:15] [main/INFO]: Compatibility level set to JAVA_16
[17:21:15] [main/INFO]: Compatibility level set to JAVA_17
[17:21:15] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'vanilla-permissions'!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'vanilla-permissions'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.21.jar:?]
        ... 3 more
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'preLaunch' provided by 'vanilla-permissions'
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.21.jar:?]
        ... 3 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: java.lang.ClassNotFoundException: com.llamalad7.mixinextras.MixinExtrasBootstrap
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:52) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.21.jar:?]
        ... 3 more
Caused by: java.lang.ClassNotFoundException: com.llamalad7.mixinextras.MixinExtrasBootstrap
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.21.jar:?]
        ... 3 more
```

**Comment by glxy14colourse** [comment]
I think i have the same issue

**Comment by glxy14colourse** [comment]
https://pastebin.com/zfgAtYLT
